### ISSUE TITLE
Andoird App crashes on resume

### ISSUE THREAD

**Issue by vikas-k-vijayakumar** [vikas-k-vijayakumar/AutonomousVehicle#1]
After the android application is minimized and resumed, it crashes. Below is the log from Android ADB.

12-28 15:21:55.923    3037-3037/com.vikas.projs.ml.autonomousvehicle I/ProcessCameraPreview? Started the applyGrayScale Method
12-28 15:21:55.983    3037-3037/com.vikas.projs.ml.autonomousvehicle I/ProcessCameraPreview? Started the onPreviewFrame Method
12-28 15:21:55.983    3037-3037/com.vikas.projs.ml.autonomousvehicle I/ProcessCameraPreview? Started the applyGrayScale Method
12-28 15:21:56.043    3037-3037/com.vikas.projs.ml.autonomousvehicle I/ProcessSensorData? Started the onResume Method
12-28 15:21:56.063    3037-3037/com.vikas.projs.ml.autonomousvehicle D/AndroidRuntime? Shutting down VM
12-28 15:21:56.063    3037-3037/com.vikas.projs.ml.autonomousvehicle W/dalvikvm? threadid=1: thread exiting with uncaught exception (group=0x40f7f930)
12-28 15:21:56.083    3037-3037/com.vikas.projs.ml.autonomousvehicle E/AndroidRuntime? FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to resume activity {com.vikas.projs.ml.autonomousvehicle/com.vikas.projs.ml.autonomousvehicle.ProcessSensorData}: java.lang.RuntimeException: Fail to connect to camera service
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2853)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2882)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Fail to connect to camera service
            at android.hardware.Camera.native_setup(Native Method)
            at android.hardware.Camera.<init>(Camera.java:410)
            at android.hardware.Camera.open(Camera.java:365)
            at com.vikas.projs.ml.autonomousvehicle.ProcessSensorData.onResume(ProcessSensorData.java:85)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1202)
            at android.app.Activity.performResume(Activity.java:5404)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2830)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2882)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
12-28 15:22:01.418    3164-3164/com.vikas.projs.ml.autonomousvehicle D/dalvikvm? Late-enabling CheckJNI
12-28 15:22:01.658    3164-3164/com.vikas.projs.ml.autonomousvehicle I/MainActivity? Started the onCreate Method
12-28 15:22:01.718    3164-3164/com.vikas.projs.ml.autonomousvehicle I/dalvikvm? Could not find method android.view.ViewGroup.onNestedScrollAccepted, referenced from method android.support.v7.internal.widget.ActionBarOverlayLayout.onNestedScrollAccepted
12-28 15:22:01.718    3164-3164/com.vikas.projs.ml.autonomousvehicle W/dalvikvm? VFY: unable to resolve virtual method 11369: Landroid/view/ViewGroup;.onNestedScrollAccepted (Landroid/view/View;Landroid/view/View;I)V
12-28 15:22:01.718    3164-3164/com.vikas.projs.ml.autonomousvehicle D/dalvikvm? VFY: replacing opcode 0x6f at 0x0000
12-28 15:22:01.718    3164-3164/com.vikas.projs.ml.autonomousvehicle I/dalvikvm? Could not find method android.view.ViewGroup.onStopNestedScroll, referenced from method android.support.v7.internal.widget.ActionBarOverlayLayout.onStopNestedScroll
12-28 15:22:01.718    3164-3164/com.vikas.projs.ml.autonomousvehicle W/dalvikvm? VFY: unable to resolve virtual method 11375: Landroid/view/ViewGroup;.onStopNestedScroll (Landroid/view/View;)V
12-28 15:22:01.718    3164-3164/com.vikas.projs.ml.autonomousvehicle D/dalvikvm? VFY: replacing opcode 0x6f at 0x0000
12-28 15:22:01.718    3164-3164/com.vikas.projs.ml.autonomousvehicle I/dalvikvm? Could not find method android.support.v7.internal.widget.ActionBarOverlayLayout.stopNestedScroll, referenced from method android.support.v7.internal.widget.ActionBarOverlayLayout.setHideOnContentScrollEnabled
12-28 15:22:01.718    3164-3164/com.vikas.projs.ml.autonomousvehicle W/dalvikvm? VFY: unable to resolve virtual method 9059: Landroid/support/v7/internal/widget/ActionBarOverlayLayout;.stopNestedScroll ()V
12-28 15:22:01.718    3164-3164/com.vikas.projs.ml.autonomousvehicle D/dalvikvm? VFY: replacing opcode 0x6e at 0x000e
12-28 15:22:01.728    3164-3164/com.vikas.projs.ml.autonomousvehicle I/dalvikvm? Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
12-28 15:22:01.728    3164-3164/com.vikas.projs.ml.autonomousvehicle W/dalvikvm? VFY: unable to resolve virtual method 368: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
12-28 15:22:01.728    3164-3164/com.vikas.projs.ml.autonomousvehicle D/dalvikvm? VFY: replacing opcode 0x6e at 0x0002
12-28 15:22:01.728    3164-3164/com.vikas.projs.ml.autonomousvehicle I/dalvikvm? Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
12-28 15:22:01.728    3164-3164/com.vikas.projs.ml.autonomousvehicle W/dalvikvm? VFY: unable to resolve virtual method 390: Landroid/content/res/TypedArray;.getType (I)I
12-28 15:22:01.728    3164-3164/com.vikas.projs.ml.autonomousvehicle D/dalvikvm? VFY: replacing opcode 0x6e at 0x0002
12-28 15:22:01.778    3164-3164/com.vikas.projs.ml.autonomousvehicle D/Switch? mDensity : 240.0
12-28 15:22:01.858    3164-3164/com.vikas.projs.ml.autonomousvehicle I/MainActivity? About to change the Visibility to: 4

**Comment by vikas-k-vijayakumar** [comment]
Workaround used as of now is as follows:
- After the app is minimized on the device, close it.
- Then touch the app icon to open the app again. Before starting the preview capture, make sure that the phone is oriented in the landscape mode.
